export default {
  './scratch/lessonA/lesson.md': {
    level: 5,   // Using different and invalid levels here, since we want to make sure they are not used
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './scratch/lessonA/lesson_nn.md': {
    level: 5,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nn',
  },
  './scratch/lessonA/lesson_en.md': {
    level: 5,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'en',
  },
  './scratch/lessonB/lesson_nb.md': { // wrong language in filename on purpose
    level: 6,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'en',
  },
  './scratch/lessonB/lesson_nn.md': { // wrong language in filename on purpose
    level: 6,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './scratch/lessonB/lesson_en.md': { // wrong language in filename on purpose
    level: 6,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nn',
  },
  './scratch/lessonC/lesson.md': {
    level: 7,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './scratch/lessonD/lesson.md': {
    level: 8,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './scratch/lessonE/lesson.md': {
    level: 5,
    author: 'Geir Arne',
    translator: 'Translator',
    language: 'nb',
  },
  './scratch/lessonF/lesson.md': {
    level: 6,
    author: 'Geir Arne',
    title: 'Title',
    language: 'nb',
  },
  './scratch/lessonG/lesson.md': {
    level: 7,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
  },
  './scratch/lessonH/lesson.md': {
    level: 8,
    author: 'Geir Arne',
    language: 'nb',
  },
  './scratch/lessonI/lesson.md': {
    level: 5,
    author: 'Geir Arne',
    translator: 'Translator',
  },
  './scratch/lessonJ/lesson.md': {
    level: 6,
    author: 'Geir Arne',
    title: 'Title',
  },
  './scratch/lessonK/lesson.md': {
    level: 7,
    author: 'Geir Arne',
  },
  './elm/lessonA/lesson.md': {
    level: 5,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './elm/lessonB/lesson.md': {
    level: 6,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './elm/lessonC/lesson.md': {
    level: 7,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './elm/lessonD/lesson.md': {
    level: 8,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './elm/lessonD/lesson_en.md': {
    level: 8,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'en',
  },
  './elm/lessonE/lesson.md': {
    level: 5,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './elm/lessonE/lesson_nn.md': {
    level: 5,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nn',
  },
  './elm/lessonE/lesson_en.md': {
    level: 5,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'en',
  },
  './elm/lessonF/lesson.md': {
    level: 6,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nb',
  },
  './elm/lessonG/lesson.md': {
    level: 7,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'nn',
  },
  './elm/lessonH/lesson.md': {
    level: 8,
    author: 'Geir Arne',
    title: 'Title',
    translator: 'Translator',
    language: 'en',
  },
};
