name: Codeclub-viewer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run tests
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Clone exercises
        run: git clone --depth=1 --branch=master https://github.com/kodeklubben/oppgaver.git ../oppgaver
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install
      - name: Run tests
        run: |
          yarn eslint
          yarn stylelint
          yarn test
      - name: Build
        run: yarn build:travis
      - name: Caching Dist Folder
        uses: actions/cache@v2
        with:
          path: ./dist
          key: cache-dist-${{ github.sha }}

  deploy:
    name: Deploy to GithubPages
    timeout-minutes: 3
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Restoring Dist Folder
        uses: actions/cache@v2
        with:
          path: ./dist
          key: cache-dist-${{ github.sha }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.NORWEGIANMANGO }}
          publish_branch: master
          publish_dir: ./dist
          cname: oppgaver.kidsakoder.no
          external_repository: kodeklubben/kodeklubben.github.io
